[package]
name = "png_filters"
description = "PNG filtering related functions"
repository = "https://github.com/Lokathor/png_filters"
version = "0.1.2"
edition = "2021"
license = "Zlib OR Apache-2.0 OR MIT"

[dev-dependencies]
getrandom = "0.2"
